### ISSUE TITLE
Inline Tipping Broken

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-site-specific-scripts#100]
The `.js-actions` selector no longer works, and as a result the inline tipping button is no longer added.

https://github.com/brave/brave-site-specific-scripts/blob/f0079aee82a4bbef217da90707208bd00f99766a/scripts/brave_rewards/publisher/twitter/tipping.ts#L280

**Comment by zenparsing** [comment]
It may be possible to get all of the information that we need from a property on one of the DOM objects. See [here](https://github.com/jonathansampson/twitter-extras) for an implementation of this idea.

**Comment by emerick** [comment]
@jonathansampson One thing to be aware of is that we did explicitly disable inline tipping on Twitter recently when we first encountered issues with their API: https://github.com/brave/brave-browser/issues/32107

**Comment by Miyayes** [comment]
Inline Tip buttons feature removed completely.
