### ISSUE TITLE
Any Option to Disable Greaselion?

### ISSUE THREAD

**Issue by cyfung1031** [brave/brave-site-specific-scripts#101]
I just want my browser to browse the site cleanly without any addon.
Is it possible to turn it off?

**Comment by bsclifton** [comment]
@cyfung1031 yes - if you visit:
brave://settings/rewards

Turn off all of the options for `Show Tip buttons on sites`

Then it shouldn't be (behind the scenes) making an extension for these

**Comment by markadrake** [comment]
This does not prevent Greaselion scripts from being injected onto the site.

![image](https://github.com/brave/brave-site-specific-scripts/assets/713355/533b0c15-f1fb-4d1c-b089-1fd4037be0ab)

![image](https://github.com/brave/brave-site-specific-scripts/assets/713355/854776f8-6205-4c3f-828f-512a63f93a95)

I assume the reference here is coming from the basic Brave install?

I can't tell if it's breaking the ad campaign management in Twitter, but it is causing me a fuss regardless.

**Comment by cyfung1031** [comment]
> @cyfung1031 yes - if you visit: brave://settings/rewards
> 
> Turn off all of the options for `Show Tip buttons on sites`
> 
> Then it shouldn't be (behind the scenes) making an extension for these

This would not stop the Greaselion scriptlets injection
Please reopen this issue

Even all ads block all brave rewards are off
Greaselion scriptlet injection never disable

However I cannot prove this in the latest Brave. 

I guess if it is really disabled,
`navigator.brave` would not be undefinded in youtube.com
